name: Test Action
on:
  push:
jobs:
  setup-versions-from-manifest:
    name: CI - py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    steps:
    # Setup Python
    # https://github.com/marketplace/actions/setup-python
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print python version
      run: python --version
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Print package list
      run: pip list
      
    - name: Install xarray
      run: pip install xarray
    - name: Print package list
      run: pip list
    - name: Test xarray
      run: python -c "import xarray; print('done')"
      
    - name: Install h5netcdf
      run: pip install h5netcdf
    - name: Print package list
      run: pip list
    - name: Test xarray
      run: python -c "import xarray; print('done')"
   
    - name: Install netcdf4
      run: pip install netcdf4
    - name: Print package list
      run: pip list
    - name: Test xarray with import of h5netcdf
      run: python -c "import h5netcdf; import xarray; print('done')" 
    - name: Test xarray
      run: python -c "import xarray; print('done')" 
